### ISSUE TITLE
PEP8 states that package names should be one word all lower case

### ISSUE THREAD

**Issue by dacb** [wesleybeckner/ECS#1]
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

`ECS_demo` should probably be `ecsdemo`

**Comment by wesleybeckner** [comment]
wow @dacb you would raise an issue that forces me to recursively grep through the whole package and rename everything and hope it all still works at the end of the day!

**Comment by wesleybeckner** [comment]
whoops tagged the commit with wrong issue number but #1 is done, did, fixed! Thanks @dacb !

**Comment by dacb** [comment]
What? @nealde says that never happens.

**Comment by nealde** [comment]
It only breaks everything like 90% of the time...

**Comment by dacb** [comment]
Then fixes, so OK, right?

With `ag` installed, I did this in bash, and yes, I used perl to fix all references:

```
function agr { ag -0 -l "$1" | xargs -0 perl -pi.bak -e "s/$1/$2/g"; }
agr EISfit eisfit
```
